export const userData = [
  {
    name: "Jan",
    "ActiveUser": 4000,
  },
  {
    name: "Feb",
    "ActiveUser": 3000,
  },
  {
    name: "Mar",
    "ActiveUser": 5000,
  },
  {
    name: "Apr",
    "ActiveUser": 4000,
  },
  {
    name: "May",
    "ActiveUser": 3000,
  },
  {
    name: "Jun",
    "ActiveUser": 2000,
  },
  {
    name: "Jul",
    "ActiveUser": 4000,
  },
  {
    name: "Aug",
    "ActiveUser": 3000,
  },
  {
    name: "Sep",
    "ActiveUser": 4000,
  },
  {
    name: "Oct",
    "ActiveUser": 1000,
  },
  {
    name: "Nov",
    "ActiveUser": 4000,
  },
  {
    name: "Dec",
    "ActiveUser": 3000,
  },
];

export const productData = [
  {
    name: "Jan",
    "Sales": 4000,
  },
  {
    name: "Feb",
    "Sales": 3000,
  },
  {
    name: "Mar",
    "Sales": 5000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 11,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 12,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 13,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 14,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 15,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 16,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 17,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 18,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 19,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 20,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 21,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 22,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 23,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 24,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 25,
    username: "Rehan Hamza",
    avatar: "/Images/Capture.PNG",
    email: "rehan553@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 11,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 12,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 13,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 14,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 15,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 16,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 17,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 18,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 19,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 20,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 21,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 22,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 23,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 24,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 25,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
];
